apiVersion: v1
kind: Service
metadata:
  name: SecretSanta
  namespace: default
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: SecretSanta
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80